module.exports = {
  creativeHand: "https://creativehand.co.in/assets/company-logo/creativeHand-no-background.png",
  creativeHandProduction: "https://creativehand.co.in/",
  creativeHandLocal: "http://localhost:3000/",
  USER_ADDED_SUCCESS: 'User Added SuccessFully',
  ADMIN_EMAIL: 'admin@thegawindustries.com',
  CAREER_EMAIL: 'careers@thegawindustries.com',
  // ADMIN_EMAIL: 'aashishbhagwat4u@gmail.com',
  // CAREER_EMAIL: 'aashishbhagwat4u@gmail.com',
  OTP_VERIFY_SUCCESS: 'Otp verified SuccessFully',
  USER_CREATED_SUCCESS: 'User Created SuccessFully',
  RAZORPAY_TEST_KEY: 'rzp_test_uPxCJhIQrZ46rn',
  RAZORPAY_TEST_SECRET: 'R9NUbTbYQ3CRsK2flKo47J3b',
  ADMIN_SUBJECT: 'Contact Form Submission | TheGAW Industries',
  CUSTOMER_SUBJECT: 'Thanks For Contacting TheGAW Industries',
};
